[package]
name = "ichart"
version = "0.1.0"
edition = "2021"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'

[dependencies]
bevy = "0.10.0"
arboard = "3.2.0"
image = "0.24.5"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"