[package]
name = "velo"
license = "MIT OR Apache-2.0"
description = "App for brainstorming & sharing ideas 🦀 Learning Project"
repository = "https://github.com/StaffEngineer/velo.git"
readme = "Readme.org"
version = "0.1.1"
edition = "2021"

exclude = ["assets/fonts/*", "velo.gif", "velo.png"]

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'

[dependencies]
bevy = "0.10.1"
bevy_prototype_lyon = "0.8.0"
base64 = "0.21.0"
serde_json = "1.0.94"
uuid = { version = "1.3.0", default-features = false, features = ["v4", "js"] }
bevy_ui_borders = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
linkify = "0.9.0"
bevy_pkv = { git = "https://github.com/johanhelsing/bevy_pkv.git", default-features = false, features = [
  "bevy",
  "rocksdb",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.2.0"
open = "4.0.1"
image = { version = "0.24.5", default-features = false, features = ["ico"] }
bevy_embedded_assets = "0.7.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
