[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2022-0048", # from xml-rs 0.8.4 - unmaintained - it's used in a build script of winit
]

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { allow = ["BSD-3-Clause"], name = "instant" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
multiple-versions = "deny"
# allowed while working with git deps
# wildcards = "deny"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    { name = "redox_syscall", version = "0.2" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/bevyengine/bevy",
]
