use bevy::prelude::*;
use std::path::PathBuf;

#[derive(Resource, Debug)]
pub struct Theme {
    pub font_color: Color,
    pub btn_border_color: Color,
    pub menu_bg: Color,
    pub menu_btn_bg: Color,
    pub left_panel_bg: Color,
    pub canvas_bg_color: Option<Color>,
    pub canvas_bg_img: Option<PathBuf>,
    pub doc_list_bg: Color,
    pub search_box_bg: Color,
    pub search_box_border: Color,
    pub add_circle_bg: Color,
    pub add_rectangle_bg: Color,
    pub remove_node_bg: Color,
    pub arrow_btn_bg: Color,
    pub test_pos_btn_bg: Color,
    pub font_back_btn_bg: Color,
    pub celebrate_btn_bg: Color,
    pub tab_bg: Color,
    pub add_tab_bg: Color,
    pub bottom_panel_bg: Color,
    pub node_bg: Color,
    pub node_border: Color,
    pub arrow_connector: Color,
    pub arrow_color: Color,
    pub selected_node_color: Color,
    pub modal_bg: Color,
    pub ok_cancel_bg: Color,
    pub ok_cancel_font: Color,
    pub shadow_color: Color,
    pub modal_text_input_bg: Color,
    pub tooltip_bg_color: Color,
}

pub fn velo_light() -> Theme {
    Theme {
        font_color: Color::rgb(0.0, 0.0, 0.0),
        btn_border_color: Color::rgb(0.5, 0.5, 0.5),
        menu_bg: Color::rgb(0.95, 0.95, 0.95),
        menu_btn_bg: Color::rgb(0.9, 0.9, 0.9),
        left_panel_bg: Color::rgb(0.98, 0.98, 0.98),
        canvas_bg_color: None,
        canvas_bg_img: Some(PathBuf::from("bg.png")),
        doc_list_bg: Color::rgb(0.95, 0.95, 0.95),
        search_box_bg: Color::rgb(0.9, 0.9, 0.9),
        search_box_border: Color::rgb(0.8, 0.8, 0.8),
        add_circle_bg: Color::rgb(0.9, 0.9, 0.9),
        add_rectangle_bg: Color::rgb(0.9, 0.9, 0.9),
        remove_node_bg: Color::rgb(0.9, 0.9, 0.9),
        arrow_btn_bg: Color::rgb(0.9, 0.9, 0.9),
        test_pos_btn_bg: Color::rgb(0.9, 0.9, 0.9),
        font_back_btn_bg: Color::rgb(0.9, 0.9, 0.9),
        celebrate_btn_bg: Color::rgb(0.9, 0.9, 0.9),
        tab_bg: Color::rgb(0.9, 0.9, 0.9),
        add_tab_bg: Color::rgb(0.9, 0.9, 0.9),
        bottom_panel_bg: Color::rgb(0.98, 0.98, 0.98),
        node_bg: Color::rgb(0.9, 0.9, 0.9),
        node_border: Color::rgb(0.8, 0.8, 0.8),
        arrow_connector: Color::rgb(0.5, 0.5, 0.5),
        arrow_color: Color::rgb(0.5, 0.5, 0.5),
        selected_node_color: Color::rgb(0.8, 0.8, 0.8),
        modal_bg: Color::rgb(0.9, 0.9, 0.9),
        ok_cancel_bg: Color::rgb(0.9, 0.9, 0.9),
        ok_cancel_font: Color::rgb(0.1, 0.1, 0.1),
        shadow_color: Color::rgb(0.98, 0.98, 0.98),
        modal_text_input_bg: Color::rgb(0.9, 0.9, 0.9),
        tooltip_bg_color: Color::rgb(0.9, 0.9, 0.9),
    }
}

pub fn velo_dark() -> Theme {
    Theme {
        font_color: Color::rgb(1.0, 1.0, 1.0),
        btn_border_color: Color::rgb(0.8, 0.8, 0.8),
        menu_bg: Color::rgb(0.15, 0.15, 0.15),
        menu_btn_bg: Color::rgb(0.2, 0.2, 0.2),
        left_panel_bg: Color::rgb(0.1, 0.1, 0.1),
        canvas_bg_color: Some(Color::rgb(0.3, 0.3, 0.3)),
        canvas_bg_img: None,
        doc_list_bg: Color::rgb(0.2, 0.2, 0.2),
        search_box_bg: Color::rgb(0.25, 0.25, 0.25),
        search_box_border: Color::rgb(0.2, 0.2, 0.2),
        add_circle_bg: Color::rgb(0.2, 0.2, 0.2),
        add_rectangle_bg: Color::rgb(0.2, 0.2, 0.2),
        remove_node_bg: Color::rgb(0.2, 0.2, 0.2),
        arrow_btn_bg: Color::rgb(0.2, 0.2, 0.2),
        test_pos_btn_bg: Color::rgb(0.2, 0.2, 0.2),
        font_back_btn_bg: Color::rgb(0.2, 0.2, 0.2),
        celebrate_btn_bg: Color::rgb(0.2, 0.2, 0.2),
        tab_bg: Color::rgb(0.2, 0.2, 0.2),
        add_tab_bg: Color::rgb(0.2, 0.2, 0.2),
        bottom_panel_bg: Color::rgb(0.1, 0.1, 0.1),
        node_bg: Color::rgb(0.2, 0.2, 0.2),
        node_border: Color::rgb(0.3, 0.3, 0.3),
        arrow_connector: Color::rgb(0.8, 0.8, 0.8),
        arrow_color: Color::rgb(0.8, 0.8, 0.8),
        selected_node_color: Color::rgb(0.3, 0.3, 0.3),
        modal_bg: Color::rgb(0.2, 0.2, 0.2),
        ok_cancel_bg: Color::rgb(0.2, 0.2, 0.2),
        ok_cancel_font: Color::rgb(0.9, 0.9, 0.9),
        shadow_color: Color::rgb(0.1, 0.1, 0.1),
        modal_text_input_bg: Color::rgb(0.2, 0.2, 0.2),
        tooltip_bg_color: Color::rgb(0.2, 0.2, 0.2),
    }
}

pub fn get_theme_by_name(theme_name: &String) -> Theme {
    match theme_name.as_str() {
        "light" => velo_light(),
        "dark" => velo_dark(),
        _ => velo_light(),
    }
}
