name: Build and Deploy WebAssembly to Web Branch
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust and wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Generate JavaScript bindings
        run: wasm-pack build --target web --out-dir out 
        
      - name: Copy WebAssembly files to web branch
        run: |
          git config --global user.email ""
          git config --global user.name "velo"
          git fetch --all
          git checkout -b web origin/web -f
          cp -r out/* .
          git add .
          git commit -m "Build and Deploy $GITHUB_SHA WebAssembly to Web Branch"
          git push origin web
